/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author nicolo.fadda
 */
public class MainGame extends javax.swing.JFrame {
    //da fare modificabile da textbox
    private int grandezza = 10;
    TableModel modello;
    Puzzle p;
    /**
     * Creates new form Inteface
     */
    public MainGame() {
        initComponents();
        p = new Puzzle(grandezza, grandezza);
 
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabPanel = new javax.swing.JTabbedPane();
        GamePanel = new javax.swing.JPanel();
        AboutText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableWords = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGrid = new javax.swing.JTable();
        SettingsPanel = new javax.swing.JPanel();
        DizionarioLabel = new javax.swing.JLabel();
        DifficoltaLabel = new javax.swing.JLabel();
        FormatoStampaLabel = new javax.swing.JLabel();
        FontLabel = new javax.swing.JLabel();
        DifficoltaToggleONOFF = new javax.swing.JToggleButton();
        Stampa2Label = new javax.swing.JButton();
        Stampa1Label = new javax.swing.JButton();
        FontScrollPanel = new javax.swing.JScrollPane();
        FontScelta = new javax.swing.JList<>();
        GeneraButton = new javax.swing.JButton();
        DizionarioFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AboutText.setText("FindTheWord");

        jTableWords.setBackground(new java.awt.Color(255, 255, 255));
        jTableWords.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));
        jTableWords.setForeground(new java.awt.Color(0, 0, 0));
        jTableWords.setName("jTableGrid"); // NOI18N
        jScrollPane1.setViewportView(jTableWords);

        jTableGrid.setBackground(new java.awt.Color(255, 255, 255));
        jTableGrid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));
        jTableGrid.setForeground(new java.awt.Color(0, 0, 0));
        jTableGrid.setName("jTableGrid"); // NOI18N
        jScrollPane2.setViewportView(jTableGrid);

        javax.swing.GroupLayout GamePanelLayout = new javax.swing.GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AboutText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(374, 374, 374))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GamePanelLayout.setVerticalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(AboutText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(71, 71, 71))
        );

        TabPanel.addTab("Game", GamePanel);

        DizionarioLabel.setText("Dizionario");

        DifficoltaLabel.setText("Difficoltà Bambini");

        FormatoStampaLabel.setText("Formato Stampa");

        FontLabel.setText("Font");

        DifficoltaToggleONOFF.setText("OFF");
        DifficoltaToggleONOFF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DifficoltaToggleONOFFItemStateChanged(evt);
            }
        });

        Stampa2Label.setText("TXT");
        Stampa2Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stampa2LabelActionPerformed(evt);
            }
        });

        Stampa1Label.setText("PNG");
        Stampa1Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stampa1LabelActionPerformed(evt);
            }
        });

        FontScelta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FontScelta.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "FONT 1", "FONT 2", "FONT 3", "FONT 4", "FONT 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        FontScelta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        FontScelta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FontScelta.setName(""); // NOI18N
        FontScrollPanel.setViewportView(FontScelta);

        GeneraButton.setText("GENERA!");
        GeneraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneraButtonActionPerformed(evt);
            }
        });

        DizionarioFile.setText("Seleziona File...");
        DizionarioFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DizionarioFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SettingsPanelLayout = new javax.swing.GroupLayout(SettingsPanel);
        SettingsPanel.setLayout(SettingsPanelLayout);
        SettingsPanelLayout.setHorizontalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsPanelLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(GeneraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SettingsPanelLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SettingsPanelLayout.createSequentialGroup()
                        .addComponent(FontLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(SettingsPanelLayout.createSequentialGroup()
                        .addComponent(FormatoStampaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                        .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingsPanelLayout.createSequentialGroup()
                                .addComponent(Stampa1Label)
                                .addGap(18, 18, 18)
                                .addComponent(Stampa2Label))
                            .addComponent(FontScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(181, 181, 181))
                    .addGroup(SettingsPanelLayout.createSequentialGroup()
                        .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SettingsPanelLayout.createSequentialGroup()
                                .addComponent(DifficoltaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DifficoltaToggleONOFF))
                            .addGroup(SettingsPanelLayout.createSequentialGroup()
                                .addComponent(DizionarioLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DizionarioFile)))
                        .addGap(208, 208, 208))))
        );
        SettingsPanelLayout.setVerticalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DizionarioLabel)
                    .addComponent(DizionarioFile))
                .addGap(84, 84, 84)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DifficoltaLabel)
                    .addComponent(DifficoltaToggleONOFF))
                .addGap(86, 86, 86)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FormatoStampaLabel)
                    .addComponent(Stampa1Label)
                    .addComponent(Stampa2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(FontLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FontScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(GeneraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        TabPanel.addTab("Settings", SettingsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void GeneraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneraButtonActionPerformed
        try {
            p.displayPuzzle();
        } catch (FileNotFoundException ex) {
            System.out.println("errore file non trovato");
        }
        DefaultTableModel dataModel = new DefaultTableModel(p.getRows(),p.getColums());
        jTableGrid.setModel(dataModel);
        char[][] puz = p.getPuzzle();
        
        for (int i = 0; i < puz.length; i++) {
            Object rowData[] = new Object[puz[i].length];
            for (int j = 0; j < puz[i].length; j++) {
                rowData[i] = puz[i][j];
            }
            ((DefaultTableModel)jTableGrid.getModel()).addRow(rowData);
        }
       
    }//GEN-LAST:event_GeneraButtonActionPerformed

    private void Stampa1LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stampa1LabelActionPerformed
        //AGGIUNGERE EVENTO CHE AL CLICK SALVA IL FILE IN FORMATO PNG
    }//GEN-LAST:event_Stampa1LabelActionPerformed

    private void Stampa2LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stampa2LabelActionPerformed
        //AGGIUNGERE EVENTO CHE AL CLICK SALVA IL FILE IN FORMATO TXT
    }//GEN-LAST:event_Stampa2LabelActionPerformed

    private void DizionarioFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DizionarioFileActionPerformed
        //AGGIUNGERE EVENTO CHE FA SCEGLIERE IL FILE CON IL DIZIONARIO
        //Uso la classe JFileChooser che mi aiuta con il mio caso
        
        //1. Creo l'oggetto JFileChooser
        JFileChooser fileChooser = new JFileChooser();
        //2. Seleziono tramite SetCurrentDirectory in quale directory l'utente
        //   si troverà al momento che cliccherà il bottone
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        //3. ShowOpenDialog serve per far aprire la finestra di scelta (dialogo)
        int result = fileChooser.showOpenDialog(this);
        //4. 
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_DizionarioFileActionPerformed

    private void DifficoltaToggleONOFFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DifficoltaToggleONOFFItemStateChanged
        //AGGIUNGERE EVENTO CHE SEGNA LO STATO DEL BOTTONE ON OFF
        if(DifficoltaToggleONOFF.isSelected()){
            DifficoltaToggleONOFF.setText("ON");
        }else{
            DifficoltaToggleONOFF.setText("OFF");
        }
    }//GEN-LAST:event_DifficoltaToggleONOFFItemStateChanged

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutText;
    private javax.swing.JLabel DifficoltaLabel;
    private javax.swing.JToggleButton DifficoltaToggleONOFF;
    private javax.swing.JButton DizionarioFile;
    private javax.swing.JLabel DizionarioLabel;
    private javax.swing.JLabel FontLabel;
    private javax.swing.JList<String> FontScelta;
    private javax.swing.JScrollPane FontScrollPanel;
    private javax.swing.JLabel FormatoStampaLabel;
    private javax.swing.JPanel GamePanel;
    private javax.swing.JButton GeneraButton;
    private javax.swing.JPanel SettingsPanel;
    private javax.swing.JButton Stampa1Label;
    private javax.swing.JButton Stampa2Label;
    private javax.swing.JTabbedPane TabPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableGrid;
    private javax.swing.JTable jTableWords;
    // End of variables declaration//GEN-END:variables
    
}

